//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:06:03 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojos.portfolio.analyses.filelist;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import com.dennismedeiros.veracode.platform.api.pojos.common.UploadedFile;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FileType")
public class UploadFile implements UploadedFile {

    @XmlAttribute(name = "file_id")
    protected Long fileId;
    @XmlAttribute(name = "file_name")
    protected String fileName;
    //@XmlAttribute(name = "file_status") // @XmlElement(name="file", type=UploadFile.class)
    //protected IStatusType fileStatus;
    @XmlAttribute(name = "file_md5")
    protected String fileMd5;

    /* (non-Javadoc)
	 * @see com.dennismedeiros.veracode.platform.parsers.jaxb.templates.filelist.IFileType#getFileId()
	 */
    @Override
	public Long getFileId() {
        return fileId;
    }

   /* (non-Javadoc)
	 * @see com.dennismedeiros.veracode.platform.parsers.jaxb.templates.filelist.IFileType#getFileName()
	 */
    @Override
	public String getFileName() {
        return fileName;
    }

    /* (non-Javadoc)
	 * @see com.dennismedeiros.veracode.platform.parsers.jaxb.templates.filelist.IFileType#getFileStatus()
	 */
//    @Override
//	public IStatusType getFileStatus() {
//        return fileStatus;
//    }

    /* (non-Javadoc)
	 * @see com.dennismedeiros.veracode.platform.parsers.jaxb.templates.filelist.IFileType#getFileMd5()
	 */
    @Override
	public String getFileMd5() {
        return fileMd5;
    }

    @Override
    public boolean equals(Object anObject) {
		boolean result = false;
		
    	if(this != anObject) {
    		if(anObject instanceof UploadFile) {
	    		UploadFile anotherFileUploaded = (UploadFile)anObject;
	    		
	    		if(anotherFileUploaded.fileName.toLowerCase().equals(this.fileName.toLowerCase()) &&
	    				anotherFileUploaded.fileMd5.equals(fileMd5)) {
	    			result = true;
	    		}
	    	}
    	} else {
    		result = true;
    	}
    	return result;
    }
    
	@Override
	public int compareTo(UploadedFile anotherFileUploadType) {
		return this.fileName.toLowerCase()
				.compareTo(anotherFileUploadType.getFileName().toLowerCase());
	}
}
