//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:25 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.portfolio.analyses.sast;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "LifecycleStageType")
@XmlEnum
public enum LifecycleStageType {

    @XmlEnumValue("Not Specified")
    NOT_SPECIFIED("Not Specified"),
    @XmlEnumValue("In Development (pre-Alpha)")
    IN_DEVELOPMENT_PRE_ALPHA("In Development (pre-Alpha)"),
    @XmlEnumValue("Internal or Alpha Testing")
    INTERNAL_OR_ALPHA_TESTING("Internal or Alpha Testing"),
    @XmlEnumValue("External or Beta Testing")
    EXTERNAL_OR_BETA_TESTING("External or Beta Testing"),
    @XmlEnumValue("Deployed (In production and actively developed)")
    DEPLOYED_IN_PRODUCTION_AND_ACTIVELY_DEVELOPED("Deployed (In production and actively developed)"),
    @XmlEnumValue("Maintenance (only bug fixes)")
    MAINTENANCE_ONLY_BUG_FIXES("Maintenance (only bug fixes)"),
    @XmlEnumValue("Cannot Disclose")
    CANNOT_DISCLOSE("Cannot Disclose");
    private final String value;

    LifecycleStageType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LifecycleStageType fromValue(String v) {
        for (LifecycleStageType c: LifecycleStageType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
