//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 11:12:48 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojos.analyses.sast;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "ModuleType")
public class ModuleFile implements Module {

    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "compiler", required = true)
    protected String compiler;
    @XmlAttribute(name = "os", required = true)
    protected String os;
    @XmlAttribute(name = "architecture", required = true)
    protected String architecture;
    @XmlAttribute(name = "loc")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger loc;
    @XmlAttribute(name = "score", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger score;
    @XmlAttribute(name = "numflawssev0", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numflawssev0;
    @XmlAttribute(name = "numflawssev1", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numflawssev1;
    @XmlAttribute(name = "numflawssev2", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numflawssev2;
    @XmlAttribute(name = "numflawssev3", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numflawssev3;
    @XmlAttribute(name = "numflawssev4", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numflawssev4;
    @XmlAttribute(name = "numflawssev5", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numflawssev5;
    @XmlAttribute(name = "target_url")
    protected String targetUrl;
    @XmlAttribute(name = "domain")
    protected String domain;
    @XmlAttribute(name = "approxlinecount")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger approxlinecount;

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#getName()
	 */
    @Override
	public String getName() {
        return name;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#setName(java.lang.String)
	 */
    @Override
	public void setName(String value) {
        this.name = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#getCompiler()
	 */
    @Override
	public String getCompiler() {
        return compiler;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#setCompiler(java.lang.String)
	 */
    @Override
	public void setCompiler(String value) {
        this.compiler = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#getOs()
	 */
    @Override
	public String getOs() {
        return os;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#setOs(java.lang.String)
	 */
    @Override
	public void setOs(String value) {
        this.os = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#getArchitecture()
	 */
    @Override
	public String getArchitecture() {
        return architecture;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#setArchitecture(java.lang.String)
	 */
    @Override
	public void setArchitecture(String value) {
        this.architecture = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#getLoc()
	 */
    @Override
	public BigInteger getLoc() {
        return loc;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#setLoc(java.math.BigInteger)
	 */
    @Override
	public void setLoc(BigInteger value) {
        this.loc = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#getScore()
	 */
    @Override
	public BigInteger getScore() {
        return score;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#setScore(java.math.BigInteger)
	 */
    @Override
	public void setScore(BigInteger value) {
        this.score = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#getNumflawssev0()
	 */
    @Override
	public BigInteger getNumflawssev0() {
        return numflawssev0;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#setNumflawssev0(java.math.BigInteger)
	 */
    @Override
	public void setNumflawssev0(BigInteger value) {
        this.numflawssev0 = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#getNumflawssev1()
	 */
    @Override
	public BigInteger getNumflawssev1() {
        return numflawssev1;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#setNumflawssev1(java.math.BigInteger)
	 */
    @Override
	public void setNumflawssev1(BigInteger value) {
        this.numflawssev1 = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#getNumflawssev2()
	 */
    @Override
	public BigInteger getNumflawssev2() {
        return numflawssev2;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#setNumflawssev2(java.math.BigInteger)
	 */
    @Override
	public void setNumflawssev2(BigInteger value) {
        this.numflawssev2 = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#getNumflawssev3()
	 */
    @Override
	public BigInteger getNumflawssev3() {
        return numflawssev3;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#setNumflawssev3(java.math.BigInteger)
	 */
    @Override
	public void setNumflawssev3(BigInteger value) {
        this.numflawssev3 = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#getNumflawssev4()
	 */
    @Override
	public BigInteger getNumflawssev4() {
        return numflawssev4;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#setNumflawssev4(java.math.BigInteger)
	 */
    @Override
	public void setNumflawssev4(BigInteger value) {
        this.numflawssev4 = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#getNumflawssev5()
	 */
    @Override
	public BigInteger getNumflawssev5() {
        return numflawssev5;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#setNumflawssev5(java.math.BigInteger)
	 */
    @Override
	public void setNumflawssev5(BigInteger value) {
        this.numflawssev5 = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#getTargetUrl()
	 */
    @Override
	public String getTargetUrl() {
        return targetUrl;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#setTargetUrl(java.lang.String)
	 */
    @Override
	public void setTargetUrl(String value) {
        this.targetUrl = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#getDomain()
	 */
    @Override
	public String getDomain() {
        return domain;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#setDomain(java.lang.String)
	 */
    @Override
	public void setDomain(String value) {
        this.domain = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#getApproxlinecount()
	 */
    @Override
	public BigInteger getApproxlinecount() {
        return approxlinecount;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IModeType#setApproxlinecount(java.math.BigInteger)
	 */
    @Override
	public void setApproxlinecount(BigInteger value) {
        this.approxlinecount = value;
    }

    @Override
    public boolean equals(Object anObject) {
    	boolean result = false;
    	
    	if (this != anObject) {
           if (anObject instanceof ModuleFile) {
    		
    			ModuleFile anotherModule = (ModuleFile) anObject;
    			if(this.name.toLowerCase().equals(anotherModule.name.toLowerCase())
    					&& this.loc.equals(anotherModule.loc)) {
    				result = true;
    			}
    		}
    	
    	} else {
    		result = true;
    	}
    		
    	return result;
    }
    
}
