//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 11:12:48 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojos.analyses.sast;

import java.util.List;

import com.dennismedeiros.veracode.platform.api.pojos.analyses.Analysis;
import com.dennismedeiros.veracode.platform.api.pojos.analyses.Find;
import com.dennismedeiros.veracode.platform.api.pojos.analyses.Weakness;

public interface StaticAnalysis extends Analysis {

	List<Module> getModules();
	Long getAnalysisSizeBytes();
	//void setAnalysisSizeBytes(Long value);
	
	
	List<Weakness> getWeaknesses();
	List<StaticAnalysisFlaw> getFlaws();
	List<Find> getFindings();
}