//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.22 at 05:14:14 PM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.portfolio;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.dennismedeiros.veracode.platform.api.pojo.ApplicationInformation;
import com.dennismedeiros.veracode.platform.api.pojo.ApplicationPortfolio;

@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "", propOrder = {
    "application"
})
@XmlRootElement(name = "appinfo")
public class ApplicationPortfolioInformationEntity implements ApplicationInformation {

    @XmlElement(type=ApplicationPortfolioEntity.class)
    protected List<ApplicationPortfolio> application;
    @XmlAttribute(name = "appinfo_version", required = true)
    protected String appinfoVersion;
    @XmlAttribute(name = "account_id", required = true)
    protected long accountId;

    @Override
	public List<ApplicationPortfolio> getApplicationPortfolios() {
        if (application == null) {
            application = new ArrayList<ApplicationPortfolio>();
        }
        return this.application;
    }

    @Override
	public String getAppinfoVersion() {
        return appinfoVersion;
    }

    @Override
	public void setAppinfoVersion(String value) {
        this.appinfoVersion = value;
    }

    @Override
	public Long getAccountId() {
        return accountId;
    }

    @Override
	public void setAccountId(Long value) {
        this.accountId = value;
    }

}
