//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.22 at 05:14:14 PM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.portfolio;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


@XmlType(name = "AppTypeType")
@XmlEnum
public enum ApplicationType {

    @XmlEnumValue("Not Specified")
    NOT_SPECIFIED("Not Specified"),
    @XmlEnumValue("Application Design/Construction/IDE/Analysis")
    APPLICATION_DESIGN_CONSTRUCTION_IDE_ANALYSIS("Application Design/Construction/IDE/Analysis"),
    @XmlEnumValue("Application Life-Cycle Management")
    APPLICATION_LIFE_CYCLE_MANAGEMENT("Application Life-Cycle Management"),
    @XmlEnumValue("Application Server/Integration Server")
    APPLICATION_SERVER_INTEGRATION_SERVER("Application Server/Integration Server"),
    @XmlEnumValue("Back-Office Enterprise")
    BACK_OFFICE_ENTERPRISE("Back-Office Enterprise"),
    CRM("CRM"),
    @XmlEnumValue("Collaboration/Groupware/Messaging")
    COLLABORATION_GROUPWARE_MESSAGING("Collaboration/Groupware/Messaging"),
    @XmlEnumValue("Consumer")
    CONSUMER("Consumer"),
    @XmlEnumValue("Content Management/Authoring")
    CONTENT_MANAGEMENT_AUTHORING("Content Management/Authoring"),
    @XmlEnumValue("Engineering")
    ENGINEERING("Engineering"),
    @XmlEnumValue("Enterprise Resource Planning")
    ENTERPRISE_RESOURCE_PLANNING("Enterprise Resource Planning"),
    @XmlEnumValue("Information Access/Delivery/Mining/Portal")
    INFORMATION_ACCESS_DELIVERY_MINING_PORTAL("Information Access/Delivery/Mining/Portal"),
    @XmlEnumValue("Information/Data Management/Database")
    INFORMATION_DATA_MANAGEMENT_DATABASE("Information/Data Management/Database"),
    @XmlEnumValue("Middleware/Message-oriented/Transaction")
    MIDDLEWARE_MESSAGE_ORIENTED_TRANSACTION("Middleware/Message-oriented/Transaction"),
    @XmlEnumValue("Network Management")
    NETWORK_MANAGEMENT("Network Management"),
    @XmlEnumValue("Networking")
    NETWORKING("Networking"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("Other Development Tools")
    OTHER_DEVELOPMENT_TOOLS("Other Development Tools"),
    @XmlEnumValue("Security")
    SECURITY("Security"),
    @XmlEnumValue("ServerWare/Clustering/Web/VM")
    SERVER_WARE_CLUSTERING_WEB_VM("ServerWare/Clustering/Web/VM"),
    @XmlEnumValue("Storage")
    STORAGE("Storage"),
    @XmlEnumValue("System-Level Software")
    SYSTEM_LEVEL_SOFTWARE("System-Level Software"),
    @XmlEnumValue("Systems Management")
    SYSTEMS_MANAGEMENT("Systems Management"),
    @XmlEnumValue("Testing Tools")
    TESTING_TOOLS("Testing Tools");
    private final String value;

    ApplicationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ApplicationType fromValue(String v) {
        for (ApplicationType c: ApplicationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
