//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.25 at 04:09:55 PM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.portfolio;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import com.dennismedeiros.veracode.platform.api.pojo.ApplicationPortfolio;
import com.dennismedeiros.veracode.platform.api.pojo.common.IndustryVerticalType;

@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "AppType")
public class ApplicationPortfolioListItem implements ApplicationPortfolio {

    @XmlAttribute(name = "app_id")
    protected Long appId;
    @XmlAttribute(name = "app_name")
    protected String appName;
    @XmlAttribute(name = "vendor_name")
    protected String vendorName;
    @XmlAttribute(name = "policy_updated_date")
    protected String policyUpdatedDate;

	public Long getId() {
        return appId;
    }

	public String getName() {
        return appName;
    }

	public String getVendorName() {
        return vendorName;
    }

    public void setVendorName(String value) {
        this.vendorName = value;
    }

	public String getPolicyUpdatedDate() {
        return policyUpdatedDate;
    }

	@Override
	public List<CustomField> getCustomfield() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setId(Long value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void setName(String value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getDescription() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setDescription(String value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public BusinessCriticalityType getBusinessCriticality() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setBusinessCriticality(BusinessCriticalityType value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getPolicy() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setPolicy(String value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void setPolicyUpdatedDate(String value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getTeams() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setTeams(String value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getOrigin() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setOrigin(String value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public IndustryVerticalType getIndustryVertical() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setIndustryVertical(IndustryVerticalType value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public ApplicationType getAppType() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setAppType(ApplicationType value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public DeploymentMethodType getDeploymentMethod() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setDeploymentMethod(DeploymentMethodType value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Boolean isIsWebApplication() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setIsWebApplication(Boolean value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getArcherAppName() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setArcherAppName(String value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getModifiedDate() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setModifiedDate(String value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Boolean isCots() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setCots(Boolean value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Boolean isVast() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setVast(Boolean value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Long getVendorId() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setVendorId(Long value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getBusinessUnit() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setBusinessUnit(String value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getBusinessOwner() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setBusinessOwner(String value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getBusinessOwnerEmail() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setBusinessOwnerEmail(String value) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getTags() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setTags(String value) {
		// TODO Auto-generated method stub
		
	}
}
