//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:25 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.portfolio.analyses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "PlatformType")
@XmlEnum
public enum PlatformType {

    @XmlEnumValue("Not Specified")
    NOT_SPECIFIED("Not Specified"),
    @XmlEnumValue("Windows")
    WINDOWS("Windows"),
    @XmlEnumValue("Solaris")
    SOLARIS("Solaris"),
    @XmlEnumValue("Linux")
    LINUX("Linux"),
    @XmlEnumValue("Java")
    JAVA("Java"),
    @XmlEnumValue("Windows Mobile")
    WINDOWS_MOBILE("Windows Mobile"),
    @XmlEnumValue("J2ME")
    J_2_ME("J2ME"),
    @XmlEnumValue("ColdFusion")
    COLD_FUSION("ColdFusion"),
    PHP("PHP"),
    @XmlEnumValue("Android")
    ANDROID("Android"),
    @XmlEnumValue("iOS")
    I_OS("iOS"),
    @XmlEnumValue("Ruby")
    RUBY("Ruby");
    private final String value;

    PlatformType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PlatformType fromValue(String v) {
        for (PlatformType c: PlatformType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
