//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:25 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.portfolio.analyses.scaninfo;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.dennismedeiros.veracode.platform.api.pojo.common.IAnalysisUnitType;
import com.dennismedeiros.veracode.platform.api.pojo.common.IBuildType;
import com.dennismedeiros.veracode.platform.api.pojo.portfolio.PolicyComplianceType;
import com.dennismedeiros.veracode.platform.api.pojo.portfolio.analyses.PlatformType;
import com.dennismedeiros.veracode.platform.api.pojo.portfolio.analyses.sast.LifecycleStageType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BuildType", propOrder = {
    "analysisUnit"
})
public class BuildType implements IBuildType {

    @XmlElement(name = "analysis_unit", type=AnalysisUnitType.class)
    protected List<IAnalysisUnitType> analysisUnit;
    @XmlAttribute(name = "version")
    protected String version;
    @XmlAttribute(name = "build_id")
    protected Long buildId;
    @XmlAttribute(name = "submitter")
    protected String submitter;
    @XmlAttribute(name = "platform")
    protected PlatformType platform;
    @XmlAttribute(name = "lifecycle_stage")
    protected LifecycleStageType lifecycleStage;
    @XmlAttribute(name = "results_ready")
    protected Boolean resultsReady;
    @XmlAttribute(name = "policy_name")
    protected String policyName;
    @XmlAttribute(name = "policy_version")
    protected BigInteger policyVersion;
    @XmlAttribute(name = "policy_compliance_status")
    protected PolicyComplianceType policyComplianceStatus;
    @XmlAttribute(name = "policy_updated_date")
    protected String policyUpdatedDate;
    @XmlAttribute(name = "rules_status")
    protected PolicyComplianceType rulesStatus;
    @XmlAttribute(name = "grace_period_expired")
    protected Boolean gracePeriodExpired;
    @XmlAttribute(name = "scan_overdue")
    protected Boolean scanOverdue;
    @XmlAttribute(name = "legacy_scan_engine")
    protected Boolean legacyScanEngine;
    @XmlAttribute(name = "launch_date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar launchDate;

    @Override
	public List<IAnalysisUnitType> getAnalysisUnit() {
        if (analysisUnit == null) {
            analysisUnit = new ArrayList<IAnalysisUnitType>();
        }
        return this.analysisUnit;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getName() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setName(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the buildId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Override
	public Long getScanId() {
        return buildId;
    }

    /**
     * Sets the value of the buildId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Override
	public void setScanId(Long value) {
        this.buildId = value;
    }

    /**
     * Gets the value of the submitter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getSubmitter() {
        return submitter;
    }

    /**
     * Sets the value of the submitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setSubmitter(String value) {
        this.submitter = value;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformType }
     *     
     */
    @Override
	public PlatformType getPlatform() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformType }
     *     
     */
    @Override
	public void setPlatform(PlatformType value) {
        this.platform = value;
    }

    /**
     * Gets the value of the lifecycleStage property.
     * 
     * @return
     *     possible object is
     *     {@link LifecycleStageType }
     *     
     */
    @Override
	public LifecycleStageType getLifecycleStage() {
        return lifecycleStage;
    }

    /**
     * Sets the value of the lifecycleStage property.
     * 
     * @param value
     *     allowed object is
     *     {@link LifecycleStageType }
     *     
     */
    @Override
	public void setLifecycleStage(LifecycleStageType value) {
        this.lifecycleStage = value;
    }

    /**
     * Gets the value of the resultsReady property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Override
	public Boolean isResultsReady() {
        return resultsReady;
    }

    /**
     * Sets the value of the resultsReady property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Override
	public void setResultsReady(Boolean value) {
        this.resultsReady = value;
    }

    /**
     * Gets the value of the policyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getPolicyName() {
        return policyName;
    }

    /**
     * Sets the value of the policyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setPolicyName(String value) {
        this.policyName = value;
    }

    /**
     * Gets the value of the policyVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Override
	public BigInteger getPolicyVersion() {
        return policyVersion;
    }

    /**
     * Sets the value of the policyVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    @Override
	public void setPolicyVersion(BigInteger value) {
        this.policyVersion = value;
    }

    /**
     * Gets the value of the policyComplianceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyComplianceType }
     *     
     */
    @Override
	public PolicyComplianceType getPolicyComplianceStatus() {
        return policyComplianceStatus;
    }

    /**
     * Sets the value of the policyComplianceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyComplianceType }
     *     
     */
    @Override
	public void setPolicyComplianceStatus(PolicyComplianceType value) {
        this.policyComplianceStatus = value;
    }

    /**
     * Gets the value of the policyUpdatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getPolicyUpdatedDate() {
        return policyUpdatedDate;
    }

    /**
     * Sets the value of the policyUpdatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setPolicyUpdatedDate(String value) {
        this.policyUpdatedDate = value;
    }

    /**
     * Gets the value of the rulesStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyComplianceType }
     *     
     */
    @Override
	public PolicyComplianceType getRulesStatus() {
        return rulesStatus;
    }

    /**
     * Sets the value of the rulesStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyComplianceType }
     *     
     */
    @Override
	public void setRulesStatus(PolicyComplianceType value) {
        this.rulesStatus = value;
    }

    /**
     * Gets the value of the gracePeriodExpired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Override
	public Boolean isGracePeriodExpired() {
        return gracePeriodExpired;
    }

    /**
     * Sets the value of the gracePeriodExpired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Override
	public void setGracePeriodExpired(Boolean value) {
        this.gracePeriodExpired = value;
    }

    /**
     * Gets the value of the scanOverdue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Override
	public Boolean isScanOverdue() {
        return scanOverdue;
    }

    /**
     * Sets the value of the scanOverdue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Override
	public void setScanOverdue(Boolean value) {
        this.scanOverdue = value;
    }

    /**
     * Gets the value of the legacyScanEngine property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Override
	public Boolean isLegacyScanEngine() {
        return legacyScanEngine;
    }

    /**
     * Sets the value of the legacyScanEngine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Override
	public void setLegacyScanEngine(Boolean value) {
        this.legacyScanEngine = value;
    }

    /**
     * Gets the value of the launchDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Override
	public XMLGregorianCalendar getLaunchDate() {
        return launchDate;
    }

    /**
     * Sets the value of the launchDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Override
	public void setLaunchDate(XMLGregorianCalendar value) {
        this.launchDate = value;
    }

}
