//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:25 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.portfolio.analyses.scaninfo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "DynamicScanType")
@XmlEnum
public enum DynamicScanType {

    @XmlEnumValue("mp") MP("mp"),
    @XmlEnumValue("ds") DS("ds");
    
    private final String value;

    DynamicScanType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DynamicScanType fromValue(String v) {
        for (DynamicScanType c: DynamicScanType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
