//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:25 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.portfolio.analyses.scaninfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.dennismedeiros.veracode.platform.api.pojo.ScanInformation;
import com.dennismedeiros.veracode.platform.api.pojo.common.IBuildType;


@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "", propOrder = {
    "build"
})
@XmlRootElement(name = "buildinfo")
public class ScanInformationEntity implements ScanInformation {

    @XmlElement( required = true, type=BuildType.class)
    protected IBuildType build;
    @XmlAttribute(name = "buildinfo_version", required = true)
    protected String buildinfoVersion;
    @XmlAttribute(name = "account_id", required = true)
    protected long accountId;
    @XmlAttribute(name = "app_id", required = true)
    protected long appId;
    @XmlAttribute(name = "sandbox_id")
    protected Long sandboxId;
    @XmlAttribute(name = "build_id", required = true)
    protected long buildId;
    @XmlAttribute(name = "dynamic_scan_type")
    protected DynamicScanType dynamicScanType;

    @Override
	public IBuildType getScan() {
        return build;
    }
    
    @Override
	public String getBuildinfoVersion() {
        return buildinfoVersion;
    }

  
    @Override
	public long getAccountId() {
        return accountId;
    }


    /**
     * Gets the value of the appId property.
     * 
     */
    @Override
	public long getAppId() {
        return appId;
    }

    /**
     * Gets the value of the sandboxId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Override
	public Long getSandboxId() {
        return sandboxId;
    }

    /**
     * Gets the value of the buildId property.
     * 
     */
    @Override
	public long getScanId() {
        return buildId;
    }
    
    /**
     * Gets the value of the dynamicScanType property.
     * 
     * @return
     *     possible object is
     *     {@link DynamicScanType }
     *     
     */
    @Override
	public DynamicScanType getDynamicScanType() {
        return dynamicScanType;
    }
}
