//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 11:12:48 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.reporting.analysis.dast;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import com.dennismedeiros.veracode.platform.api.pojo.portfolio.analyses.scaninfo.DynamicScanType;
import com.dennismedeiros.veracode.platform.api.pojo.reporting.analysis.AnalysisReport;

@XmlAccessorType(XmlAccessType.NONE)
public class DynamicAnalysisReport extends AnalysisReport implements DynamicAnalysis {

	//@XmlElementWrapper(name = "modules")
    //@XmlElement(name="module", type=ModuleFile.class)
	//private List<Module> modules;
        
    @XmlAttribute(name = "rating", required = true)
    protected String rating;
    @XmlAttribute(name = "score", required = true)
    protected BigInteger score;
    @XmlAttribute(name = "mitigated_rating")
    protected String mitigatedRating;
    @XmlAttribute(name = "mitigated_score")
    protected BigInteger mitigatedScore;
    @XmlAttribute(name = "submitted_date", required = true)
    protected String submittedDate;
    @XmlAttribute(name = "published_date")
    protected String publishedDate;
    @XmlAttribute(name = "next_scan_due")
    protected String nextScanDue;
    @XmlAttribute(name = "analysis_size_bytes")
    protected Long analysisSizeBytes;
    @XmlAttribute(name = "engine_version")
    protected String engineVersion;
    @XmlAttribute(name = "dynamic_scan_type")
    protected DynamicScanType dynamicScanType;
    @XmlAttribute(name = "scan_exit_status_id")
    protected BigInteger scanExitStatusId;
    @XmlAttribute(name = "scan_exit_status_desc")
    protected String scanExitStatusDesc;

   
    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getRating()
	 */
    @Override
	public String getRating() {
        return rating;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getScore()
	 */
    @Override
	public BigInteger getScore() {
        return score;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getMitigatedRating()
	 */
    @Override
	public String getMitigatedRating() {
        return mitigatedRating;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getMitigatedScore()
	 */
    @Override
	public BigInteger getMitigatedScore() {
        return mitigatedScore;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getSubmittedDate()
	 */
    @Override
	public String getSubmittedDate() {
        return submittedDate;
    }
    
    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getNextScanDue()
	 */
    @Override
	public String getNextScanDue() {
        return nextScanDue;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getEngineVersion()
	 */
    @Override
	public String getEngineVersion() {
        return engineVersion;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getDynamicScanType()
	 */
    @Override
	public DynamicScanType getDynamicScanType() {
        return dynamicScanType;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#setDynamicScanType(com.veracode.platform.parsers.jaxb.templates.detailedreport.DynamicScanType)
	 */
    @Override
	public void setDynamicScanType(DynamicScanType value) {
        this.dynamicScanType = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getScanExitStatusId()
	 */
    @Override
	public BigInteger getScanExitStatusId() {
        return scanExitStatusId;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getScanExitStatusDesc()
	 */
    @Override
	public String getScanExitStatusDesc() {
        return scanExitStatusDesc;
    }
}
