//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:11:01 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.portfolio.sandboxInfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sandbox"
})
@XmlRootElement(name = "sandboxinfo")
public class SandboxInformation {

    @XmlElement(required = true)
    protected SandboxType sandbox;
    @XmlAttribute(name = "sandboxinfo_version", required = true)
    protected String sandboxinfoVersion;
    @XmlAttribute(name = "account_id", required = true)
    protected long accountId;
    @XmlAttribute(name = "app_id", required = true)
    protected long appId;
    @XmlAttribute(name = "build_id")
    protected Long buildId;
    @XmlAttribute(name = "analysis_id")
    protected Long analysisId;
    @XmlAttribute(name = "analysis_unit_id")
    protected Long analysisUnitId;

    /**
     * Gets the value of the sandbox property.
     * 
     * @return
     *     possible object is
     *     {@link SandboxType }
     *     
     */
    public SandboxType getSandbox() {
        return sandbox;
    }

    /**
     * Sets the value of the sandbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link SandboxType }
     *     
     */
    public void setSandbox(SandboxType value) {
        this.sandbox = value;
    }

    /**
     * Gets the value of the sandboxinfoVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSandboxinfoVersion() {
        return sandboxinfoVersion;
    }

    /**
     * Sets the value of the sandboxinfoVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSandboxinfoVersion(String value) {
        this.sandboxinfoVersion = value;
    }

    /**
     * Gets the value of the accountId property.
     * 
     */
    public long getAccountId() {
        return accountId;
    }

    /**
     * Sets the value of the accountId property.
     * 
     */
    public void setAccountId(long value) {
        this.accountId = value;
    }

    /**
     * Gets the value of the appId property.
     * 
     */
    public long getAppId() {
        return appId;
    }

    /**
     * Sets the value of the appId property.
     * 
     */
    public void setAppId(long value) {
        this.appId = value;
    }

    /**
     * Gets the value of the buildId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBuildId() {
        return buildId;
    }

    /**
     * Sets the value of the buildId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBuildId(Long value) {
        this.buildId = value;
    }

    /**
     * Gets the value of the analysisId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAnalysisId() {
        return analysisId;
    }

    /**
     * Sets the value of the analysisId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAnalysisId(Long value) {
        this.analysisId = value;
    }

    /**
     * Gets the value of the analysisUnitId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAnalysisUnitId() {
        return analysisUnitId;
    }

    /**
     * Sets the value of the analysisUnitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAnalysisUnitId(Long value) {
        this.analysisUnitId = value;
    }

}
