//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:11:01 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.portfolio.sandboxInfo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SandboxType", propOrder = {
    "customfield"
})
public class SandboxType {

    protected List<CustomFieldType> customfield;
    @XmlAttribute(name = "sandbox_id", required = true)
    protected long sandboxId;
    @XmlAttribute(name = "sandbox_name")
    protected String sandboxName;
    @XmlAttribute(name = "sandbox_status")
    protected String sandboxStatus;
    @XmlAttribute(name = "owner", required = true)
    protected String owner;
    @XmlAttribute(name = "modified_date", required = true)
    protected String modifiedDate;
    @XmlAttribute(name = "created_date", required = true)
    protected String createdDate;

    /**
     * Gets the value of the customfield property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customfield property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomfield().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomFieldType }
     * 
     * 
     */
    public List<CustomFieldType> getCustomfield() {
        if (customfield == null) {
            customfield = new ArrayList<CustomFieldType>();
        }
        return this.customfield;
    }

    /**
     * Gets the value of the sandboxId property.
     * 
     */
    public long getSandboxId() {
        return sandboxId;
    }

    /**
     * Sets the value of the sandboxId property.
     * 
     */
    public void setSandboxId(long value) {
        this.sandboxId = value;
    }

    /**
     * Gets the value of the sandboxName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSandboxName() {
        return sandboxName;
    }

    /**
     * Sets the value of the sandboxName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSandboxName(String value) {
        this.sandboxName = value;
    }

    /**
     * Gets the value of the sandboxStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSandboxStatus() {
        return sandboxStatus;
    }

    /**
     * Sets the value of the sandboxStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSandboxStatus(String value) {
        this.sandboxStatus = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the modifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedDate() {
        return modifiedDate;
    }

    /**
     * Sets the value of the modifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedDate(String value) {
        this.modifiedDate = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedDate(String value) {
        this.createdDate = value;
    }

}
