//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.03 at 10:56:01 AM EST 
//


package com.dennismedeiros.veracode.platform.api.pojo.reporting.analysis.sast.datapath;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The call element contains the data path number, 
 * 				file name, function name, and line number of 
 * 				each call in the call stack.
 *             
 * 
 * <p>Java class for CallType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CallType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="data_path" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="file_name" type="{https://analysiscenter.veracode.com/schema/2.0/callstacks}LongTextType" />
 *       &lt;attribute name="file_path" type="{https://analysiscenter.veracode.com/schema/2.0/callstacks}LongRequiredTextType" />
 *       &lt;attribute name="function_name" type="{https://analysiscenter.veracode.com/schema/2.0/callstacks}LongRequiredTextType" />
 *       &lt;attribute name="line_number" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="relative_location" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CallType")
public class CallType {

    @XmlAttribute(name = "data_path")
    protected Long dataPath;
    @XmlAttribute(name = "file_name")
    protected String fileName;
    @XmlAttribute(name = "file_path")
    protected String filePath;
    @XmlAttribute(name = "function_name")
    protected String functionName;
    @XmlAttribute(name = "line_number")
    protected Long lineNumber;
    @XmlAttribute(name = "relative_location")
    protected Integer relativeLocation;

    /**
     * Gets the value of the dataPath property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDataPath() {
        return dataPath;
    }

    /**
     * Sets the value of the dataPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDataPath(Long value) {
        this.dataPath = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the filePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * Sets the value of the filePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilePath(String value) {
        this.filePath = value;
    }

    /**
     * Gets the value of the functionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * Sets the value of the functionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctionName(String value) {
        this.functionName = value;
    }

    /**
     * Gets the value of the lineNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLineNumber() {
        return lineNumber;
    }

    /**
     * Sets the value of the lineNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLineNumber(Long value) {
        this.lineNumber = value;
    }

    /**
     * Gets the value of the relativeLocation property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRelativeLocation() {
        return relativeLocation;
    }

    /**
     * Sets the value of the relativeLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRelativeLocation(Integer value) {
        this.relativeLocation = value;
    }

}
