//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.22 at 05:14:14 PM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojos.portfolio;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.dennismedeiros.veracode.platform.api.pojos.ApplicationPortfolio;
import com.dennismedeiros.veracode.platform.api.pojos.common.IndustryVerticalType;
import com.dennismedeiros.veracode.platform.api.pojos.reporting.common.CustomField;

@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "ApplicationType", propOrder = {
    "customfield"
})
public class ApplicationPortfolioEntity implements ApplicationPortfolio {

	@XmlElement(name="customerfield", type=CustomFieldType.class)
    protected List<CustomField> customfield;
    @XmlAttribute(name = "app_id")
    protected Long appId;
    @XmlAttribute(name = "app_name")
    protected String appName;
    @XmlAttribute(name = "vendor")
    protected String vendor;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "business_criticality")
    protected BusinessCriticalityType businessCriticality;
    @XmlAttribute(name = "policy")
    protected String policy;
    @XmlAttribute(name = "policy_updated_date")
    protected String policyUpdatedDate;
    @XmlAttribute(name = "teams")
    protected String teams;
    @XmlAttribute(name = "origin")
    protected String origin;
    @XmlAttribute(name = "industry_vertical")
    protected IndustryVerticalType industryVertical;
    @XmlAttribute(name = "app_type")
    protected ApplicationType appType;
    @XmlAttribute(name = "deployment_method")
    protected DeploymentMethodType deploymentMethod;
    @XmlAttribute(name = "is_web_application")
    protected Boolean isWebApplication;
    @XmlAttribute(name = "archer_app_name")
    protected String archerAppName;
    @XmlAttribute(name = "modified_date")
    protected String modifiedDate;
    @XmlAttribute(name = "cots")
    protected Boolean cots;
    @XmlAttribute(name = "vast")
    protected Boolean vast;
    @XmlAttribute(name = "vendor_id")
    protected Long vendorId;
    @XmlAttribute(name = "business_unit")
    protected String businessUnit;
    @XmlAttribute(name = "business_owner")
    protected String businessOwner;
    @XmlAttribute(name = "business_owner_email")
    protected String businessOwnerEmail;
    @XmlAttribute(name = "tags")
    protected String tags;

    @Override
	public List<CustomField> getCustomfield() {
        if (customfield == null) {
            customfield = new ArrayList<CustomField>();
        }
        return this.customfield;
    }

    /**
     * Gets the value of the appId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Override
	public Long getId() {
        return appId;
    }

    /**
     * Sets the value of the appId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Override
	public void setId(Long value) {
        this.appId = value;
    }

    /**
     * Gets the value of the appName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getName() {
        return appName;
    }

    /**
     * Sets the value of the appName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setName(String value) {
        this.appName = value;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getVendorName() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setVendorName(String value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the businessCriticality property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessCriticalityType }
     *     
     */
    @Override
	public BusinessCriticalityType getBusinessCriticality() {
        return businessCriticality;
    }

    /**
     * Sets the value of the businessCriticality property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessCriticalityType }
     *     
     */
    @Override
	public void setBusinessCriticality(BusinessCriticalityType value) {
        this.businessCriticality = value;
    }

    /**
     * Gets the value of the policy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getPolicy() {
        return policy;
    }

    /**
     * Sets the value of the policy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setPolicy(String value) {
        this.policy = value;
    }

    /**
     * Gets the value of the policyUpdatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getPolicyUpdatedDate() {
        return policyUpdatedDate;
    }

    /**
     * Sets the value of the policyUpdatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setPolicyUpdatedDate(String value) {
        this.policyUpdatedDate = value;
    }

    /**
     * Gets the value of the teams property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getTeams() {
        return teams;
    }

    /**
     * Sets the value of the teams property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setTeams(String value) {
        this.teams = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setOrigin(String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the industryVertical property.
     * 
     * @return
     *     possible object is
     *     {@link IndustryVerticalType }
     *     
     */
    @Override
	public IndustryVerticalType getIndustryVertical() {
        return industryVertical;
    }

    /**
     * Sets the value of the industryVertical property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndustryVerticalType }
     *     
     */
    @Override
	public void setIndustryVertical(IndustryVerticalType value) {
        this.industryVertical = value;
    }

    /**
     * Gets the value of the appType property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationType }
     *     
     */
    @Override
	public ApplicationType getAppType() {
        return appType;
    }

    /**
     * Sets the value of the appType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationType }
     *     
     */
    @Override
	public void setAppType(ApplicationType value) {
        this.appType = value;
    }

    /**
     * Gets the value of the deploymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link DeploymentMethodType }
     *     
     */
    @Override
	public DeploymentMethodType getDeploymentMethod() {
        return deploymentMethod;
    }

    /**
     * Sets the value of the deploymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeploymentMethodType }
     *     
     */
    @Override
	public void setDeploymentMethod(DeploymentMethodType value) {
        this.deploymentMethod = value;
    }

    /**
     * Gets the value of the isWebApplication property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Override
	public Boolean isIsWebApplication() {
        return isWebApplication;
    }

    /**
     * Sets the value of the isWebApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Override
	public void setIsWebApplication(Boolean value) {
        this.isWebApplication = value;
    }

    /**
     * Gets the value of the archerAppName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getArcherAppName() {
        return archerAppName;
    }

    /**
     * Sets the value of the archerAppName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setArcherAppName(String value) {
        this.archerAppName = value;
    }

    /**
     * Gets the value of the modifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getModifiedDate() {
        return modifiedDate;
    }

    /**
     * Sets the value of the modifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setModifiedDate(String value) {
        this.modifiedDate = value;
    }

    /**
     * Gets the value of the cots property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Override
	public Boolean isCots() {
        return cots;
    }

    /**
     * Sets the value of the cots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Override
	public void setCots(Boolean value) {
        this.cots = value;
    }

    /**
     * Gets the value of the vast property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Override
	public Boolean isVast() {
        return vast;
    }

    /**
     * Sets the value of the vast property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Override
	public void setVast(Boolean value) {
        this.vast = value;
    }

    /**
     * Gets the value of the vendorId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Override
	public Long getVendorId() {
        return vendorId;
    }

    /**
     * Sets the value of the vendorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Override
	public void setVendorId(Long value) {
        this.vendorId = value;
    }

    /**
     * Gets the value of the businessUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getBusinessUnit() {
        return businessUnit;
    }

    /**
     * Sets the value of the businessUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setBusinessUnit(String value) {
        this.businessUnit = value;
    }

    /**
     * Gets the value of the businessOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getBusinessOwner() {
        return businessOwner;
    }

    /**
     * Sets the value of the businessOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setBusinessOwner(String value) {
        this.businessOwner = value;
    }

    /**
     * Gets the value of the businessOwnerEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getBusinessOwnerEmail() {
        return businessOwnerEmail;
    }

    /**
     * Sets the value of the businessOwnerEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setBusinessOwnerEmail(String value) {
        this.businessOwnerEmail = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setTags(String value) {
        this.tags = value;
    }
}
