//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.25 at 04:09:55 PM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojos.portfolio;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import com.dennismedeiros.veracode.platform.api.pojos.accounts.LoginAccountType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserType")
public class UserAccount implements User {

    @XmlAttribute(name = "login_account_type", required = true)//login_account_type
    protected LoginAccountType loginAccountType;
    @XmlAttribute(name = "username", required = true)
    protected String username;
    @XmlAttribute(name = "create_application_profile", required = true)
    protected boolean createApplicationProfile;
    @XmlAttribute(name = "create_sandbox", required = true)
    protected boolean createSandbox;
    @XmlAttribute(name = "create_new_build", required = true)
    protected boolean createNewBuild;
    @XmlAttribute(name = "create_policy_scan", required = true)
    protected boolean createPolicyScan;
    @XmlAttribute(name = "create_sandbox_scan", required = true)
    protected boolean createSandboxScan;
    @XmlAttribute(name = "assign_app_to_team", required = true)
    protected boolean assignAppToTeam;
    @XmlAttribute(name = "assign_app_to_any_team", required = true)
    protected boolean assignAppToAnyTeam;
    @XmlAttribute(name = "view_sandbox", required = true)
    protected boolean viewSandbox;
    @XmlAttribute(name = "view_results", required = true)
    protected boolean viewResults;
    @XmlAttribute(name = "approve_mitigations", required = true)
    protected boolean approveMitigations;
    @XmlAttribute(name = "submit_static_scan", required = true)
    protected boolean submitStaticScan;
    @XmlAttribute(name = "submit_policy_static_scan", required = true)
    protected boolean submitPolicyStaticScan;
    @XmlAttribute(name = "submit_sandbox_static_scan", required = true)
    protected boolean submitSandboxStaticScan;

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#getLoginAccountType()
	 */
    @Override
	public LoginAccountType getLoginAccountType() {
        return loginAccountType;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#setLoginAccountType(com.veracode.platform.parsers.jaxb.templates.applicatonlist.LoginAccountType)
	 */
//    @Override
//	public void setLoginAccountType(LoginAccountType value) {
//        this.loginAccountType = value;
//    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#getUsername()
	 */
    @Override
	public String getUsername() {
        return username;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#setUsername(java.lang.String)
	 */
//    @Override
//	public void setUsername(String value) {
//        this.username = value;
//    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#isCreateApplicationProfile()
	 */
    @Override
	public boolean isCreateApplicationProfile() {
        return createApplicationProfile;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#setCreateApplicationProfile(boolean)
	 */
//    @Override
//	public void setCreateApplicationProfile(boolean value) {
//        this.createApplicationProfile = value;
//    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#isCreateSandbox()
	 */
    @Override
	public boolean isCreateSandbox() {
        return createSandbox;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#setCreateSandbox(boolean)
	 */
//    @Override
//	public void setCreateSandbox(boolean value) {
//        this.createSandbox = value;
//    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#isCreateNewBuild()
	 */
    @Override
	public boolean isCreateNewBuild() {
        return createNewBuild;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#setCreateNewBuild(boolean)
	 */
//    @Override
//	public void setCreateNewBuild(boolean value) {
//        this.createNewBuild = value;
//    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#isCreatePolicyScan()
	 */
    @Override
	public boolean isCreatePolicyScan() {
        return createPolicyScan;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#setCreatePolicyScan(boolean)
	 */
//    @Override
//	public void setCreatePolicyScan(boolean value) {
//        this.createPolicyScan = value;
//    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#isCreateSandboxScan()
	 */
    @Override
	public boolean isCreateSandboxScan() {
        return createSandboxScan;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#setCreateSandboxScan(boolean)
	 */
//    @Override
//	public void setCreateSandboxScan(boolean value) {
//        this.createSandboxScan = value;
//    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#isAssignAppToTeam()
	 */
    @Override
	public boolean isAssignAppToTeam() {
        return assignAppToTeam;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#setAssignAppToTeam(boolean)
	 */
//    @Override
//	public void setAssignAppToTeam(boolean value) {
//        this.assignAppToTeam = value;
//    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#isAssignAppToAnyTeam()
	 */
    @Override
	public boolean isAssignAppToAnyTeam() {
        return assignAppToAnyTeam;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#setAssignAppToAnyTeam(boolean)
	 */
//    @Override
//	public void setAssignAppToAnyTeam(boolean value) {
//        this.assignAppToAnyTeam = value;
//    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#isViewSandbox()
	 */
    @Override
	public boolean isViewSandbox() {
        return viewSandbox;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#setViewSandbox(boolean)
	 */
//    @Override
//	public void setViewSandbox(boolean value) {
//        this.viewSandbox = value;
//    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#isViewResults()
	 */
    @Override
	public boolean isViewResults() {
        return viewResults;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#setViewResults(boolean)
	 */
//    @Override
//	public void setViewResults(boolean value) {
//        this.viewResults = value;
//    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#isApproveMitigations()
	 */
    @Override
	public boolean isApproveMitigations() {
        return approveMitigations;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#setApproveMitigations(boolean)
	 */
//    @Override
//	public void setApproveMitigations(boolean value) {
//        this.approveMitigations = value;
//    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#isSubmitStaticScan()
	 */
    @Override
	public boolean isSubmitStaticScan() {
        return submitStaticScan;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#setSubmitStaticScan(boolean)
	 */
//    @Override
//	public void setSubmitStaticScan(boolean value) {
//        this.submitStaticScan = value;
//    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#isSubmitPolicyStaticScan()
	 */
    @Override
	public boolean isSubmitPolicyStaticScan() {
        return submitPolicyStaticScan;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#setSubmitPolicyStaticScan(boolean)
	 */
//    @Override
//	public void setSubmitPolicyStaticScan(boolean value) {
//        this.submitPolicyStaticScan = value;
//    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#isSubmitSandboxStaticScan()
	 */
    @Override
	public boolean isSubmitSandboxStaticScan() {
        return submitSandboxStaticScan;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.IUserType#setSubmitSandboxStaticScan(boolean)
	 */
//    @Override
//	public void setSubmitSandboxStaticScan(boolean value) {
//        this.submitSandboxStaticScan = value;
//    }

}
