//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.22 at 05:14:14 PM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "IndustryVerticalType")
@XmlEnum
public enum IndustryVerticalType {

    @XmlEnumValue("Not Specified")
    NOT_SPECIFIED("Not Specified"),
    @XmlEnumValue("Aerospace")
    AEROSPACE("Aerospace"),
    @XmlEnumValue("Agriculture")
    AGRICULTURE("Agriculture"),
    @XmlEnumValue("Apparel")
    APPAREL("Apparel"),
    @XmlEnumValue("Automotive and Transport")
    AUTOMOTIVE_AND_TRANSPORT("Automotive and Transport"),
    @XmlEnumValue("Banking")
    BANKING("Banking"),
    @XmlEnumValue("Beverages")
    BEVERAGES("Beverages"),
    @XmlEnumValue("Biotechnology")
    BIOTECHNOLOGY("Biotechnology"),
    @XmlEnumValue("Business Services")
    BUSINESS_SERVICES("Business Services"),
    @XmlEnumValue("Charitable Organizations")
    CHARITABLE_ORGANIZATIONS("Charitable Organizations"),
    @XmlEnumValue("Chemicals")
    CHEMICALS("Chemicals"),
    @XmlEnumValue("Communications")
    COMMUNICATIONS("Communications"),
    @XmlEnumValue("Computer Hardware")
    COMPUTER_HARDWARE("Computer Hardware"),
    @XmlEnumValue("Software")
    SOFTWARE("Software"),
    @XmlEnumValue("Consulting")
    CONSULTING("Consulting"),
    @XmlEnumValue("Construction")
    CONSTRUCTION("Construction"),
    @XmlEnumValue("Consumer Products Manufacturers")
    CONSUMER_PRODUCTS_MANUFACTURERS("Consumer Products Manufacturers"),
    @XmlEnumValue("Consumer Services")
    CONSUMER_SERVICES("Consumer Services"),
    @XmlEnumValue("Cultural Institutions")
    CULTURAL_INSTITUTIONS("Cultural Institutions"),
    @XmlEnumValue("Education")
    EDUCATION("Education"),
    @XmlEnumValue("Electronics")
    ELECTRONICS("Electronics"),
    @XmlEnumValue("Energy")
    ENERGY("Energy"),
    @XmlEnumValue("Engineering")
    ENGINEERING("Engineering"),
    @XmlEnumValue("Environmental")
    ENVIRONMENTAL("Environmental"),
    @XmlEnumValue("Finance")
    FINANCE("Finance"),
    @XmlEnumValue("Food & Beverage")
    FOOD_BEVERAGE("Food & Beverage"),
    @XmlEnumValue("Foundations")
    FOUNDATIONS("Foundations"),
    @XmlEnumValue("Government")
    GOVERNMENT("Government"),
    @XmlEnumValue("Healthcare")
    HEALTHCARE("Healthcare"),
    @XmlEnumValue("Hospitality")
    HOSPITALITY("Hospitality"),
    @XmlEnumValue("Manufacturing")
    MANUFACTURING("Manufacturing"),
    @XmlEnumValue("Insurance")
    INSURANCE("Insurance"),
    @XmlEnumValue("Recreation")
    RECREATION("Recreation"),
    @XmlEnumValue("Machinery")
    MACHINERY("Machinery"),
    @XmlEnumValue("Media & Entertainment")
    MEDIA_ENTERTAINMENT("Media & Entertainment"),
    @XmlEnumValue("Membership Organizations")
    MEMBERSHIP_ORGANIZATIONS("Membership Organizations"),
    @XmlEnumValue("Metals and Mining")
    METALS_AND_MINING("Metals and Mining"),
    @XmlEnumValue("Pharmaceuticals")
    PHARMACEUTICALS("Pharmaceuticals"),
    @XmlEnumValue("Real Estate")
    REAL_ESTATE("Real Estate"),
    @XmlEnumValue("Retail")
    RETAIL("Retail"),
    @XmlEnumValue("Security Products and Services")
    SECURITY_PRODUCTS_AND_SERVICES("Security Products and Services"),
    @XmlEnumValue("Technology")
    TECHNOLOGY("Technology"),
    @XmlEnumValue("Telecommunications Equipment")
    TELECOMMUNICATIONS_EQUIPMENT("Telecommunications Equipment"),
    @XmlEnumValue("Telecommunications")
    TELECOMMUNICATIONS("Telecommunications"),
    @XmlEnumValue("Transportation")
    TRANSPORTATION("Transportation"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("Utilities")
    UTILITIES("Utilities");
    private final String value;

    IndustryVerticalType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IndustryVerticalType fromValue(String v) {
        for (IndustryVerticalType c: IndustryVerticalType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
