//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 11:12:48 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.reporting.analysis;

import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.List;
import java.util.TimeZone;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlTransient;

@XmlAccessorType(XmlAccessType.NONE)
public abstract class AnalysisReport implements Analysis {
    
	@XmlAttribute(name = "rating", required = true)
    protected String rating;
    @XmlAttribute(name = "score", required = true)
    protected BigInteger score;
    @XmlAttribute(name = "mitigated_rating")
    protected String mitigatedRating;
    @XmlAttribute(name = "mitigated_score")
    protected BigInteger mitigatedScore;
    @XmlAttribute(name = "submitted_date", required = true)
    protected String submittedDate;
    @XmlAttribute(name = "published_date")
    protected String publishedDate;
    @XmlAttribute(name = "next_scan_due")
    protected String nextScanDue;
    @XmlAttribute(name = "engine_version")
    protected String engineVersion;
    @XmlAttribute(name = "scan_exit_status_id")
    protected BigInteger scanExitStatusId;
    @XmlAttribute(name = "scan_exit_status_desc")
    protected String scanExitStatusDesc;
    @XmlAttribute(name = "version")
    protected String scanName;
    
	@XmlTransient protected Long id;
	@XmlTransient protected List<Find> findings;
    
	@Override
	public Long getId() {
		return id;
	}
	
    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getEngineVersion()
	 */
    @Override
	public String getEngineVersion() {
        return engineVersion;
    }

    @Override
	public List<Find> getFindings() {
		return this.findings;
	}
    
    protected void setFindings(List<Find> finds) {
    	this.findings = finds;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getMitigatedRating()
	 */
    @Override
	public String getMitigatedRating() {
        return mitigatedRating;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getMitigatedScore()
	 */
    @Override
	public BigInteger getMitigatedScore() {
        return mitigatedScore;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getVersion()
	 */
    @Override
	public String getName() {
        return scanName;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getNextScanDue()
	 */
    @Override
	public String getNextScanDue() {
        return nextScanDue;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getPublishedDate()
	 */
    @Override
	public Instant getPublishedDate() {
        return translateUTC(this.publishedDate);
    }
    
    private Instant translateUTC(String utcDateTime) {
    	Instant resultTime = Instant.now();
    	
    	try {
			String time = utcDateTime.substring(0, utcDateTime.indexOf("UTC"));
			SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
			sdf.setTimeZone(TimeZone.getTimeZone("UTC"));
			
			resultTime = sdf.parse(time).toInstant();
		} catch (ParseException e) {
			//TODO: logger.error(e.getMessage());
		}
		return resultTime;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getRating()
	 */
    @Override
	public String getRating() {
        return rating;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getScanExitStatusDesc()
	 */
    @Override
	public String getScanExitStatusDesc() {
        return scanExitStatusDesc;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getScanExitStatusId()
	 */
    @Override
	public BigInteger getScanExitStatusId() {
        return scanExitStatusId;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getScore()
	 */
    @Override
	public BigInteger getScore() {
        return score;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnalysisType#getSubmittedDate()
	 */
    @Override
	public String getSubmittedDate() {
        return submittedDate;
    }
}
