//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:10:12 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.portfolio.analyses.prescan;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModuleType", propOrder = {
    "issue",
    "fileIssue"
})
public class ModuleFile {

    protected List<IssueType> issue;
    @XmlElement(name = "file_issue")
    protected List<FileIssue> fileIssue;
    @XmlAttribute(name = "id")
    protected Long id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "app_file_id")
    protected Long appFileId;
    @XmlAttribute(name = "checksum")
    protected String checksum;
    @XmlAttribute(name = "platform")
    protected String platform;
    @XmlAttribute(name = "size")
    protected String size;
    @XmlAttribute(name = "status")
    protected String status;
    @XmlAttribute(name = "has_fatal_errors")
    protected Boolean hasFatalErrors;
    @XmlAttribute(name = "is_dependency")
    protected Boolean isDependency;

    /**
     * Gets the value of the issue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the issue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIssue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IssueType }
     * 
     * 
     */
    public List<IssueType> getIssues() {
        if (issue == null) {
            issue = new ArrayList<IssueType>();
        }
        return this.issue;
    }

    public List<FileIssue> getFileIssues() {
        if (fileIssue == null) {
            fileIssue = new ArrayList<FileIssue>();
        }
        return this.fileIssue;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getId() {
        return id;
    }
    
    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Gets the value of the appFileId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAppFileId() {
        return appFileId;
    }

    /**
     * Gets the value of the checksum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChecksum() {
        return checksum;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSize() {
        return size;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Gets the value of the hasFatalErrors property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean hasFatalErrors() {
        return hasFatalErrors;
    }

     /**
     * Gets the value of the isDependency property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDependency() {
        return isDependency;
    }

    @Override
    public boolean equals(Object anObject) {
    	boolean result = false;
    	
    	if (this != anObject) {
           if (anObject instanceof ModuleFile) {
    		
    			ModuleFile anotherModule = (ModuleFile) anObject;
    			if(this.name.toLowerCase().equals(anotherModule.name.toLowerCase())
    					//TODO Verify Checksum meaning
    					&& this.checksum.equals(anotherModule.checksum)
    					) {
    				result = true;
    			}
    		}
    	} else {
    		result = true;
    	}
    		
    	return result;
    }
}
