//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:10:12 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.portfolio.analyses.prescan;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class PrescanResultsObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.veracode.platform.parsers.jaxb.templates.prescan
     * 
     */
    public PrescanResultsObjectFactory() {
    }

    /**
     * Create an instance of {@link Prescanresults }
     * 
     */
    public PrescanResults createPrescanresults() {
        return new PrescanResults();
    }

    /**
     * Create an instance of {@link ModuleFile }
     * 
     */
    public ModuleFile createModuleType() {
        return new ModuleFile();
    }

    /**
     * Create an instance of {@link IssueType }
     * 
     */
    public IssueType createIssueType() {
        return new IssueType();
    }

    /**
     * Create an instance of {@link FileIssue }
     * 
     */
    public FileIssue createFileIssueType() {
        return new FileIssue();
    }

}
