//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:25 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojos.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "StatusType")
@XmlEnum
public enum AnalysisStatusType {

    @XmlEnumValue("Incomplete")
    INCOMPLETE("Incomplete"),
    @XmlEnumValue("Not Submitted to Engine")
    NOT_SUBMITTED_TO_ENGINE("Not Submitted to Engine"),
    @XmlEnumValue("Submitted to Engine")
    SUBMITTED_TO_ENGINE("Submitted to Engine"),
    @XmlEnumValue("Scan Errors")
    SCAN_ERRORS("Scan Errors"),
    @XmlEnumValue("Scan In Process")
    SCAN_IN_PROCESS("Scan In Process"),
    @XmlEnumValue("Scan Cancelled")
    SCAN_CANCELLED("Scan Cancelled"),
    @XmlEnumValue("Scan Internal Error")
    SCAN_INTERNAL_ERROR("Scan Internal Error"),
    @XmlEnumValue("Pending Internal Review")
    PENDING_INTERNAL_REVIEW("Pending Internal Review"),
    @XmlEnumValue("Results Ready")
    RESULTS_READY("Results Ready"),
    @XmlEnumValue("Pre-Scan Submitted")
    PRE_SCAN_SUBMITTED("Pre-Scan Submitted"),
    @XmlEnumValue("Pre-Scan Failed")
    PRE_SCAN_FAILED("Pre-Scan Failed"),
    @XmlEnumValue("Pre-Scan Success")
    PRE_SCAN_SUCCESS("Pre-Scan Success"),
    @XmlEnumValue("No Modules Defined")
    NO_MODULES_DEFINED("No Modules Defined"),
    @XmlEnumValue("Pending Vendor Confirmation")
    PENDING_VENDOR_CONFIRMATION("Pending Vendor Confirmation"),
    @XmlEnumValue("Vendor Reviewing")
    VENDOR_REVIEWING("Vendor Reviewing"),
    @XmlEnumValue("Pre-Scan Cancelled")
    PRE_SCAN_CANCELLED("Pre-Scan Cancelled"),
    @XmlEnumValue("Scan On Hold")
    SCAN_ON_HOLD("Scan On Hold");
    private final String value;

    AnalysisStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AnalysisStatusType fromValue(String v) {
        for (AnalysisStatusType c: AnalysisStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
