//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:25 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojos.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "AnalysisType")
@XmlEnum
public enum AnalysisType {

    @XmlEnumValue("Static")  STATIC("Static"),
    @XmlEnumValue("Dynamic") DYNAMIC("Dynamic"),
    @XmlEnumValue("Manual")  MANUAL("Manual"),
    @XmlEnumValue("eDAST")   E_DAST("eDAST");
    
    private final String value;

    AnalysisType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AnalysisType fromValue(String v) {
        for (AnalysisType c: AnalysisType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
