//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 11:12:48 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojos.reporting.common;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name="category")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder = {
    "desc",
    "recommendations",
    "cwe"
})
public class WeaknessCategory implements Category {

    @XmlElement(required = true, type=ParagraphSequence.class)
    protected ParagraphList desc;
    @XmlElement(required = true, type=ParagraphSequence.class)
    protected ParagraphList recommendations;
    @XmlElement(required = true, type=CweTopic.class)
    protected List<CweCategory> cwe;
    @XmlAttribute(name = "categoryid", required = true)
    protected BigInteger categoryid;
    @XmlAttribute(name = "categoryname", required = true)
    protected String categoryname;
    @XmlAttribute(name = "pcirelated")
    protected Boolean pcirelated;

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.ICategoryType#getDesc()
	 */
    @Override
	public ParagraphList getDesc() {
        return desc;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.ICategoryType#getRecommendations()
	 */
    @Override
	public ParagraphList getRecommendations() {
        return recommendations;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.ICategoryType#getCwe()
	 */
    @Override
	public List<CweCategory> getCWEs() {
        if (cwe == null) {
            cwe = new ArrayList<CweCategory>();
        }
        return this.cwe;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.ICategoryType#getCategoryid()
	 */
    @Override
	public BigInteger getCategoryid() {
        return categoryid;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.ICategoryType#getCategoryname()
	 */
    @Override
	public String getName() {
        return categoryname;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.ICategoryType#isPcirelated()
	 */
    @Override
	public Boolean isPcirelated() {
        return pcirelated;
    }
}
