//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:25 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojos.portfolio.analyses.scaninfo;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.dennismedeiros.veracode.platform.api.pojos.common.IAnalysisUnitType;
import com.dennismedeiros.veracode.platform.api.pojos.common.AnalysisStatusType;
import com.dennismedeiros.veracode.platform.api.pojos.common.AnalysisType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnalysisUnitType")
public class AnalysisUnitType implements IAnalysisUnitType {

    @XmlAttribute(name = "analysis_type")
    protected AnalysisType analysisType;
    @XmlAttribute(name = "published_date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar publishedDate;
    @XmlAttribute(name = "published_date_sec")
    protected BigInteger publishedDateSec;
    @XmlAttribute(name = "status")
    protected AnalysisStatusType status;
    @XmlAttribute(name = "estimated_scan_hours")
    protected BigInteger estimatedScanHours;
    @XmlAttribute(name = "estimated_delivery_date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar estimatedDeliveryDate;
    @XmlAttribute(name = "engine_version")
    protected String engineVersion;

    @Override
	public AnalysisType getAnalysisType() {
        return analysisType;
    }

    @Override
	public void setAnalysisType(AnalysisType value) {
        this.analysisType = value;
    }

    @Override
	public XMLGregorianCalendar getPublishedDate() {
        return publishedDate;
    }

    /**
     * Sets the value of the publishedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Override
	public void setPublishedDate(XMLGregorianCalendar value) {
        this.publishedDate = value;
    }

    /**
     * Gets the value of the publishedDateSec property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Override
	public BigInteger getPublishedDateSec() {
        return publishedDateSec;
    }

    /**
     * Sets the value of the publishedDateSec property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    @Override
	public void setPublishedDateSec(BigInteger value) {
        this.publishedDateSec = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisStatusType }
     *     
     */
    @Override
	public AnalysisStatusType getStatus() {
        return status;
    }

    @Override
	public void setStatus(AnalysisStatusType value) {
        this.status = value;
    }

    @Override
	public BigInteger getEstimatedScanHours() {
        return estimatedScanHours;
    }

    @Override
	public void setEstimatedScanHours(BigInteger value) {
        this.estimatedScanHours = value;
    }
    
    @Override
	public XMLGregorianCalendar getEstimatedDeliveryDate() {
        return estimatedDeliveryDate;
    }

    /**
     * Sets the value of the estimatedDeliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Override
	public void setEstimatedDeliveryDate(XMLGregorianCalendar value) {
        this.estimatedDeliveryDate = value;
    }

    /**
     * Gets the value of the engineVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getEngineVersion() {
        return engineVersion;
    }

    /**
     * Sets the value of the engineVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setEngineVersion(String value) {
        this.engineVersion = value;
    }

}
