package com.dennismedeiros.veracode.platform.api.pojos.portfolio.analyses.scaninfo;

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:25 AM EDT 
//

//@javax.xml.bind.annotation.XmlSchema(namespace = "https://analysiscenter.veracode.com/schema/4.0/buildinfo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
//
