//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:06:03 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.portfolio.analyses.filelist;

import javax.xml.bind.annotation.XmlRegistry;

import com.dennismedeiros.veracode.platform.api.pojo.common.UploadedFile;

@XmlRegistry
public class FileListObjectFactory {


    /**
     * Create a new FileListObjectFactory that can be used to create new instances of schema derived classes for package: com.veracode.platform.parsers.jaxb.templates.filelist
     * 
     */
    public FileListObjectFactory() {
    }

    /**
     * Create an instance of {@link UploadFileContent }
     * 
     */
    public UploadedContent createFilelist() {
        return new UploadFileContent();
    }

    /**
     * Create an instance of {@link UploadFile }
     * 
     */
    public UploadedFile createFileType() {
        return new UploadFile();
    }

}
