//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 11:12:48 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.analyses.mast;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ManualAnalysisType", propOrder = {
    "ciaAdjustment",
    "deliveryConsultant"})
    ///"modules"
//})
public class ManualAnalysisReport implements ManualAnalysis {

    @XmlElement(name = "cia_adjustment")
    protected Integer ciaAdjustment;
    @XmlElement(name = "delivery_consultant")
    protected List<String> deliveryConsultant;
    //@XmlElement(required = true)
    //protected Modules modules;
    @XmlAttribute(name = "rating", required = true)
    protected String rating;
    @XmlAttribute(name = "score", required = true)
    protected BigInteger score;
    @XmlAttribute(name = "mitigated_rating")
    protected String mitigatedRating;
    @XmlAttribute(name = "mitigated_score")
    protected BigInteger mitigatedScore;
    @XmlAttribute(name = "submitted_date", required = true)
    protected String submittedDate;
    @XmlAttribute(name = "published_date")
    protected String publishedDate;
    @XmlAttribute(name = "next_scan_due")
    protected String nextScanDue;
    @XmlAttribute(name = "version")
    protected String version;

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#getCiaAdjustment()
	 */
    @Override
	public Integer getCiaAdjustment() {
        return ciaAdjustment;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#setCiaAdjustment(java.lang.Integer)
	 */
    @Override
	public void setCiaAdjustment(Integer value) {
        this.ciaAdjustment = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#getDeliveryConsultant()
	 */
    @Override
	public List<String> getDeliveryConsultant() {
        if (deliveryConsultant == null) {
            deliveryConsultant = new ArrayList<String>();
        }
        return this.deliveryConsultant;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#getModules()
	 */
    //@Override
	//public IModes getModules() {
     //   return modules;
    //}

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#setModules(com.veracode.platform.parsers.jaxb.templates.detailedreport.ManualAnalysisType.Modules)
	 */
    //@Override
	//public void setModules(IModes value) {
    //    this.modules = value;
   // }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#getRating()
	 */
    @Override
	public String getRating() {
        return rating;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#setRating(java.lang.String)
	 */
    @Override
	public void setRating(String value) {
        this.rating = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#getScore()
	 */
    @Override
	public BigInteger getScore() {
        return score;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#setScore(java.math.BigInteger)
	 */
    @Override
	public void setScore(BigInteger value) {
        this.score = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#getMitigatedRating()
	 */
    @Override
	public String getMitigatedRating() {
        return mitigatedRating;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#setMitigatedRating(java.lang.String)
	 */
    @Override
	public void setMitigatedRating(String value) {
        this.mitigatedRating = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#getMitigatedScore()
	 */
    @Override
	public BigInteger getMitigatedScore() {
        return mitigatedScore;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#setMitigatedScore(java.math.BigInteger)
	 */
    @Override
	public void setMitigatedScore(BigInteger value) {
        this.mitigatedScore = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#getSubmittedDate()
	 */
    @Override
	public String getSubmittedDate() {
        return submittedDate;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#setSubmittedDate(java.lang.String)
	 */
    @Override
	public void setSubmittedDate(String value) {
        this.submittedDate = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#getPublishedDate()
	 */
    @Override
	public String getPublishedDate() {
        return publishedDate;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#setPublishedDate(java.lang.String)
	 */
    @Override
	public void setPublishedDate(String value) {
        this.publishedDate = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#getNextScanDue()
	 */
    @Override
	public String getNextScanDue() {
        return nextScanDue;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#setNextScanDue(java.lang.String)
	 */
    @Override
	public void setNextScanDue(String value) {
        this.nextScanDue = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#getVersion()
	 */
    @Override
	public String getVersion() {
        return version;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IManualAnalysis#setVersion(java.lang.String)
	 */
    @Override
	public void setVersion(String value) {
        this.version = value;
    }

    /*
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "module"
    })
    public static class Modules implements IModules {

        protected List<IModuleType> module;

        @Override
		public List<IModuleType> getModule() {
            if (module == null) {
                module = new ArrayList<IModuleType>();
            }
            return this.module;
        }
    }
     */
}
