//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 11:12:48 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.analyses.mast;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


@XmlType(name = "ScreenshotFormatType")
@XmlEnum
public enum ScreenshotFormatType {

    GIF,
    JPG,
    PNG;

    public String value() {
        return name();
    }

    public static ScreenshotFormatType fromValue(String v) {
        return valueOf(v);
    }

}
