//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.25 at 04:09:55 PM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojos.accounts;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "LoginAccountType")
@XmlEnum
public enum LoginAccountType {

    @XmlEnumValue("user") USER("user"),
    @XmlEnumValue("api")  API("api");
    
    private final String value;

    LoginAccountType(String v) {
        value = v;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.applicatonlist.ILoginType#value()
	 */
    @Override
	public String toString() {
        return value;
    }

    public static LoginAccountType fromValue(String v) {
        for (LoginAccountType c: LoginAccountType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
