//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.22 at 04:52:16 PM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.portfolio.analyses.scanlist;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.dennismedeiros.veracode.platform.api.pojo.Scan;
import com.dennismedeiros.veracode.platform.api.pojo.Scans;

@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "", propOrder = {
    "build"
})
@XmlRootElement(name = "buildlist")
public class ScanList implements Scans {

	@XmlElement(name="build", type=ScanEntity.class)
    protected List<Scan> build;
	
    @XmlAttribute(name = "buildlist_version", required = true)
    protected String buildlistVersion;
    @XmlAttribute(name = "account_id", required = true)
    protected long accountId;
    @XmlAttribute(name = "app_id", required = true)
    protected long appId;
    @XmlAttribute(name = "sandbox_id")
    protected Long sandboxId;
    @XmlAttribute(name = "app_name", required = true)
    protected String appName;

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.scanlist.IScanList#getScans()
	 */
    @Override
	public List<Scan> getScans() {
        if (build == null) {
            build = new ArrayList<Scan>();
        }
        return this.build;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.scanlist.IScanList#getScanListVersion()
	 */
    @Override
	public String getScanListVersion() {
        return buildlistVersion;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.scanlist.IScanList#getAccountId()
	 */
    @Override
	public Long getAccountId() {
        return accountId;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.scanlist.IScanList#getAppId()
	 */
    @Override
	public Long getAppId() {
        return appId;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.scanlist.IScanList#getAppName()
	 */
    @Override
	public String getAppName() {
        return appName;
    }
}
