//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 11:12:48 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.analyses.sca;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "SoftwareCompositionAnalysis", propOrder = {
    "vulnerableComponents"
})
public class SoftwareCompositionAnalysisReport implements SoftwareCompositionAnalysis {

    @XmlElement(name = "vulnerable_components", type=VulnerableComponentList.class)
    protected IVulnerableComponentList vulnerableComponents;
    @XmlAttribute(name = "third_party_components", required = true)
    protected BigInteger thirdPartyComponents;
    @XmlAttribute(name = "violate_policy", required = true)
    protected boolean violatePolicy;
    @XmlAttribute(name = "components_violated_policy", required = true)
    protected BigInteger componentsViolatedPolicy;

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.ISofwareCompositionAnalysis#getVulnerableComponents()
	 */
    @Override
	public IVulnerableComponentList getVulnerableComponents() {
        return vulnerableComponents;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.ISofwareCompositionAnalysis#setVulnerableComponents(com.veracode.platform.parsers.jaxb.templates.detailedreport.VulnerableComponentList)
	 */
    @Override
	public void setVulnerableComponents(IVulnerableComponentList value) {
        this.vulnerableComponents = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.ISofwareCompositionAnalysis#getThirdPartyComponents()
	 */
    @Override
	public BigInteger getThirdPartyComponents() {
        return thirdPartyComponents;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.ISofwareCompositionAnalysis#setThirdPartyComponents(java.math.BigInteger)
	 */
    @Override
	public void setThirdPartyComponents(BigInteger value) {
        this.thirdPartyComponents = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.ISofwareCompositionAnalysis#isViolatePolicy()
	 */
    @Override
	public boolean isViolatePolicy() {
        return violatePolicy;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.ISofwareCompositionAnalysis#setViolatePolicy(boolean)
	 */
    @Override
	public void setViolatePolicy(boolean value) {
        this.violatePolicy = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.ISofwareCompositionAnalysis#getComponentsViolatedPolicy()
	 */
    @Override
	public BigInteger getComponentsViolatedPolicy() {
        return componentsViolatedPolicy;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.ISofwareCompositionAnalysis#setComponentsViolatedPolicy(java.math.BigInteger)
	 */
    @Override
	public void setComponentsViolatedPolicy(BigInteger value) {
        this.componentsViolatedPolicy = value;
    }

}
