//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 11:12:48 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojos.reporting.findings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MitigationListType", propOrder = {
    "mitigation"
})
public class MitigationListType implements MitigationList {

	@XmlElement(name="mitigation", type = MitigationType.class)
    protected List<Mitigation> mitigation;

    /**
     * Gets the value of the mitigation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mitigation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMitigation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MitigationType }
     * 
     * 
     */
    @Override
	public List<Mitigation> getMitigations() {
        if (mitigation == null) {
            mitigation = new ArrayList<Mitigation>();
        }
        return this.mitigation;
    }

}
