//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 11:12:48 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.reporting.common;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.dennismedeiros.veracode.platform.api.pojo.reporting.analysis.mast.IAnnotationListType;
import com.dennismedeiros.veracode.platform.api.pojo.reporting.analysis.mast.IAnnotationType;


@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "AnnotationListType", propOrder = {
    "annotation"
})
public class AnnotationListType implements IAnnotationListType {

	@XmlElement(name="annotation", type=AnnotationType.class)
    protected List<IAnnotationType> annotation;

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IAnnotationListType#getAnnotation()
	 */
    @Override
	public List<IAnnotationType> getAnnotation() {
        if (annotation == null) {
            annotation = new ArrayList<IAnnotationType>();
        }
        return this.annotation;
    }

}
