//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 11:12:48 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.reporting.common;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 *       The element describes summary data for the flaws in the build.
 *       Each adjustment will have the following attributes:
 *       * new:  The number of flaws first found in this build of the application.
 *       * reopen:  The number of flaws found in a prior build of the application 
 *         that were not new, but were not found in the build immediately prior to
 *         this build.
 *       * open:  The number of flaws found in this build that were also found in the
 *         build immediately prior to this build.
 *       * cannot-reproduce: The number of dynamic vulnerabilities reported in a previous 
 *       	dynamic scan that could not be verified as fixed.
 *       * fixed:  The number of flaws found in the prior build that were not found 
 *       	in the current build. Dynamic vulnerabilities are verified as fixed.
 *       * total:  The total number of flaws found in this build.
 *       * not_mitigated:  The total number of flaws found in this build that are 
 *         not mitigated.
 *       * sev-1-change: The number of Severity 1 flaws found in this build, 
 *         minus the number of Severity 1 flaws found in the build immediately prior
 *         to this build.
 *       * sev-2-change: The number of Severity 2 flaws found in this build, 
 *         minus the number of Severity 2 flaws found in the build immediately prior
 *         to this build.
 *       * sev-3-change: The number of Severity 3 flaws found in this build, 
 *         minus the number of Severity 3 flaws found in the build immediately prior
 *         to this build.
 *       * sev-4-change: The number of Severity 4 flaws found in this build, 
 *         minus the number of Severity 4 flaws found in the build immediately prior
 *         to this build.
 *       * sev-5-change: The number of Severity 5 flaws found in this build, 
 *         minus the number of Severity 5 flaws found in the build immediately prior
 *         to this build.
 *       * conforms-to-guidelines: The total number of mitigations reviewed by Veracode 
 *         that adhere to the risk tolerance guidelines you established.
 *       * deviates-from-guidelines: The total number of mitigations reviewed by Veracode
 *         that either do not provide enough information, or do not adhere to the risk
 *         tolerance guidelines you established.
 *       * total-reviewed-mitigations: The total number of mitigations reviewed by Veracode.
 *         This may not add up to the total number of all proposed or accepted mitigations.
 *     
 * 
 * <p>Java class for FlawStatusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlawStatusType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="new" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="reopen" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="open" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="cannot-reproduce" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="fixed" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="total" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="not_mitigated" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="sev-1-change" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="sev-2-change" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="sev-3-change" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="sev-4-change" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="sev-5-change" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="conforms-to-guidelines" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="deviates-from-guidelines" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="total-reviewed-mitigations" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlawStatusType")
public class FlawStatusSummary implements FlawStatus {

    @XmlAttribute(name = "new", required = true)
    protected BigInteger _new;
    @XmlAttribute(name = "reopen", required = true)
    protected BigInteger reopen;
    @XmlAttribute(name = "open", required = true)
    protected BigInteger open;
    @XmlAttribute(name = "cannot-reproduce")
    protected BigInteger cannotReproduce;
    @XmlAttribute(name = "fixed", required = true)
    protected BigInteger fixed;
    @XmlAttribute(name = "total", required = true)
    protected BigInteger total;
    @XmlAttribute(name = "not_mitigated", required = true)
    protected BigInteger notMitigated;
    @XmlAttribute(name = "sev-1-change", required = true)
    protected BigInteger sev1Change;
    @XmlAttribute(name = "sev-2-change", required = true)
    protected BigInteger sev2Change;
    @XmlAttribute(name = "sev-3-change", required = true)
    protected BigInteger sev3Change;
    @XmlAttribute(name = "sev-4-change", required = true)
    protected BigInteger sev4Change;
    @XmlAttribute(name = "sev-5-change", required = true)
    protected BigInteger sev5Change;
    @XmlAttribute(name = "conforms-to-guidelines")
    protected BigInteger conformsToGuidelines;
    @XmlAttribute(name = "deviates-from-guidelines")
    protected BigInteger deviatesFromGuidelines;
    @XmlAttribute(name = "total-reviewed-mitigations")
    protected BigInteger totalReviewedMitigations;

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#getNew()
	 */
    @Override
	public BigInteger getNew() {
        return _new;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#setNew(java.math.BigInteger)
	 */
    @Override
	public void setNew(BigInteger value) {
        this._new = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#getReopen()
	 */
    @Override
	public BigInteger getReopen() {
        return reopen;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#setReopen(java.math.BigInteger)
	 */
    @Override
	public void setReopen(BigInteger value) {
        this.reopen = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#getOpen()
	 */
    @Override
	public BigInteger getOpen() {
        return open;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#setOpen(java.math.BigInteger)
	 */
    @Override
	public void setOpen(BigInteger value) {
        this.open = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#getCannotReproduce()
	 */
    @Override
	public BigInteger getCannotReproduce() {
        return cannotReproduce;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#setCannotReproduce(java.math.BigInteger)
	 */
    @Override
	public void setCannotReproduce(BigInteger value) {
        this.cannotReproduce = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#getFixed()
	 */
    @Override
	public BigInteger getFixed() {
        return fixed;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#setFixed(java.math.BigInteger)
	 */
    @Override
	public void setFixed(BigInteger value) {
        this.fixed = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#getTotal()
	 */
    @Override
	public BigInteger getTotal() {
        return total;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#setTotal(java.math.BigInteger)
	 */
    @Override
	public void setTotal(BigInteger value) {
        this.total = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#getNotMitigated()
	 */
    @Override
	public BigInteger getNotMitigated() {
        return notMitigated;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#setNotMitigated(java.math.BigInteger)
	 */
    @Override
	public void setNotMitigated(BigInteger value) {
        this.notMitigated = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#getSev1Change()
	 */
    @Override
	public BigInteger getSev1Change() {
        return sev1Change;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#setSev1Change(java.math.BigInteger)
	 */
    @Override
	public void setSev1Change(BigInteger value) {
        this.sev1Change = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#getSev2Change()
	 */
    @Override
	public BigInteger getSev2Change() {
        return sev2Change;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#setSev2Change(java.math.BigInteger)
	 */
    @Override
	public void setSev2Change(BigInteger value) {
        this.sev2Change = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#getSev3Change()
	 */
    @Override
	public BigInteger getSev3Change() {
        return sev3Change;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#setSev3Change(java.math.BigInteger)
	 */
    @Override
	public void setSev3Change(BigInteger value) {
        this.sev3Change = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#getSev4Change()
	 */
    @Override
	public BigInteger getSev4Change() {
        return sev4Change;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#setSev4Change(java.math.BigInteger)
	 */
    @Override
	public void setSev4Change(BigInteger value) {
        this.sev4Change = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#getSev5Change()
	 */
    @Override
	public BigInteger getSev5Change() {
        return sev5Change;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#setSev5Change(java.math.BigInteger)
	 */
    @Override
	public void setSev5Change(BigInteger value) {
        this.sev5Change = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#getConformsToGuidelines()
	 */
    @Override
	public BigInteger getConformsToGuidelines() {
        return conformsToGuidelines;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#setConformsToGuidelines(java.math.BigInteger)
	 */
    @Override
	public void setConformsToGuidelines(BigInteger value) {
        this.conformsToGuidelines = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#getDeviatesFromGuidelines()
	 */
    @Override
	public BigInteger getDeviatesFromGuidelines() {
        return deviatesFromGuidelines;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#setDeviatesFromGuidelines(java.math.BigInteger)
	 */
    @Override
	public void setDeviatesFromGuidelines(BigInteger value) {
        this.deviatesFromGuidelines = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#getTotalReviewedMitigations()
	 */
    @Override
	public BigInteger getTotalReviewedMitigations() {
        return totalReviewedMitigations;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IFlawStatusType#setTotalReviewedMitigations(java.math.BigInteger)
	 */
    @Override
	public void setTotalReviewedMitigations(BigInteger value) {
        this.totalReviewedMitigations = value;
    }

}
