//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 11:12:48 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.reporting.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


@XmlType(name = "PolicyRuleType")
@XmlEnum
public enum PolicyRuleType {

    @XmlEnumValue("Disallow Vulnerabilities by Severity")
    DISALLOW_VULNERABILITIES_BY_SEVERITY("Disallow Vulnerabilities by Severity"),
    @XmlEnumValue("Disallow CVSS Score")
    DISALLOW_CVSS_SCORE("Disallow CVSS Score"),
    @XmlEnumValue("Disallow Component Blacklist")
    DISALLOW_COMPONENT_BLACKLIST("Disallow Component Blacklist");
    private final String value;

    PolicyRuleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PolicyRuleType fromValue(String v) {
        for (PolicyRuleType c: PolicyRuleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
