//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 11:12:48 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.reporting.common;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "ParaType", propOrder = {
    "bulletitem"
})
public class Prose implements Paragraph {

    protected List<Sentence> bulletitem;
    @XmlAttribute(name = "text", required = true)
    protected String text;

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IParaType#getBulletitem()
	 */
    @Override
    @XmlElement(name="bulletitem", type=Phrase.class)
	public List<Sentence> getBulletitem() {
        if (bulletitem == null) {
            bulletitem = new ArrayList<Sentence>();
        }
        return this.bulletitem;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IParaType#getText()
	 */
    @Override
	public String getText() {
        return text;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.IParaType#setText(java.lang.String)
	 */
    @Override
	public void setText(String value) {
        this.text = value;
    }

}
