//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 11:12:48 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.reporting.common;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * @author Dennis Medeiros
 *
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlType(propOrder = {
    "category"
})
public class SeverityLevel implements Severity {

	@XmlElement(name="category", type=WeaknessCategory.class)
    protected List<Category> category;
    
    @XmlAttribute(name = "level", required = true)
    protected int level;

    @Override
	public List<Category> getCategories() {
        if (category == null) {
            category = new ArrayList<Category>();
        }
        return this.category;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.ISeverityType#getLevel()
	 */
    @Override
	public int getLevel() {
        return level;
    }

    /* (non-Javadoc)
	 * @see com.veracode.platform.parsers.jaxb.templates.detailedreport.ISeverityType#setLevel(int)
	 */
    @Override
	public void setLevel(int value) {
        this.level = value;
    }

}
