//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.20 at 12:34:34 PM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.portfolio.analyses.mitigations;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "ActionTypeType")
@XmlEnum
public enum MitigationAction {

    @XmlEnumValue("comment")
    COMMENT("comment"),
    @XmlEnumValue("fp")
    FP("fp"),
    @XmlEnumValue("appdesign")
    APPDESIGN("appdesign"),
    @XmlEnumValue("osenv")
    OSENV("osenv"),
    @XmlEnumValue("netenv")
    NETENV("netenv"),
    @XmlEnumValue("rejected")
    REJECTED("rejected"),
    @XmlEnumValue("accepted")
    ACCEPTED("accepted"),
    @XmlEnumValue("remediated")
    REMEDIATED("remediated"),
    @XmlEnumValue("noactiontaken")
    NOACTIONTAKEN("noactiontaken"),
    @XmlEnumValue("conforms")
    CONFORMS("conforms"),
    @XmlEnumValue("deviates")
    DEVIATES("deviates");
    private final String value;

    MitigationAction(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MitigationAction fromValue(String v) {
        for (MitigationAction c: MitigationAction.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
