//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.20 at 12:34:34 PM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.portfolio.analyses.mitigations;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class MitigationInfoObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.veracode.api.mitigations
     * 
     */
    public MitigationInfoObjectFactory() {
    }

    /**
     * Create an instance of {@link MitigationInfo }
     * 
     */
    public MitigationInfo createMitigationinfo() {
        return new MitigationInfo();
    }

    /**
     * Create an instance of {@link Issue }
     * 
     */
    public Issue createIssueType() {
        return new Issue();
    }

    /**
     * Create an instance of {@link ErrorMessage }
     * 
     */
    public ErrorMessage createErrorType() {
        return new ErrorMessage();
    }

    /**
     * Create an instance of {@link MitigationEntry }
     * 
     */
    public Mitigation createMitigationActionType() {
        return new MitigationEntry();
    }

}
