package com.dennismedeiros.veracode.platform.api.pojo.portfolio.analyses.mitigations;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.20 at 12:34:34 PM EDT 
//

//@javax.xml.bind.annotation.XmlSchema(namespace = "https://analysiscenter.veracode.com/schema/mitigationinfo/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
//package com.veracode.api.parsers.jaxb.templates.mitigations;
