//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:11:35 AM EDT 
//


package com.dennismedeiros.veracode.platform.api.pojo.portfolio.sandboxes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.dennismedeiros.veracode.platform.api.pojo.Sandbox;
import com.dennismedeiros.veracode.platform.api.pojo.Sandboxes;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sandbox"
})
@XmlRootElement(name = "sandboxlist")
public class SandboxList implements Sandboxes {

	@XmlElement(name="sandbox", type=SandboxEntity.class)
    protected List<Sandbox> sandbox;
    @XmlAttribute(name = "sandboxlist_version", required = true)
    protected String sandboxlistVersion;
    @XmlAttribute(name = "account_id", required = true)
    protected long accountId;
    @XmlAttribute(name = "app_id", required = true)
    protected long appId;

    /* (non-Javadoc)
	 * @see com.veracode.api.parsers.jaxb.templates.sandboxlist.ISandboxList#getSandbox()
	 */
    @Override
	public List<Sandbox> getSandboxes() {
        if (sandbox == null) {
            sandbox = new ArrayList<Sandbox>();
        }
        return this.sandbox;
    }

    /* (non-Javadoc)
	 * @see com.veracode.api.parsers.jaxb.templates.sandboxlist.ISandboxList#getSandboxlistVersion()
	 */
    @Override
	public String getSandboxlistVersion() {
        return sandboxlistVersion;
    }

    /* (non-Javadoc)
	 * @see com.veracode.api.parsers.jaxb.templates.sandboxlist.ISandboxList#setSandboxlistVersion(java.lang.String)
	 */
    @Override
	public void setSandboxlistVersion(String value) {
        this.sandboxlistVersion = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.api.parsers.jaxb.templates.sandboxlist.ISandboxList#getAccountId()
	 */
    @Override
	public long getAccountId() {
        return accountId;
    }

    /* (non-Javadoc)
	 * @see com.veracode.api.parsers.jaxb.templates.sandboxlist.ISandboxList#setAccountId(long)
	 */
    @Override
	public void setAccountId(Long value) {
        this.accountId = value;
    }

    /* (non-Javadoc)
	 * @see com.veracode.api.parsers.jaxb.templates.sandboxlist.ISandboxList#getAppId()
	 */
    @Override
	public long getAppId() {
        return appId;
    }

    /* (non-Javadoc)
	 * @see com.veracode.api.parsers.jaxb.templates.sandboxlist.ISandboxList#setAppId(long)
	 */
    @Override
	public void setAppId(Long value) {
        this.appId = value;
    }

}
