//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.03 at 10:56:01 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://analysiscenter.veracode.com/schema/2.0/callstacks", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.dennismedeiros.veracode.platform.api.pojos.analyses.sast.datapath;
